# Generated by Django 5.2.7 on 2025-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACCION', 'Acción'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('SCI-FI', 'Ciencia Ficción'), ('ROMANCE', 'Romance')], max_length=50),
        ),
    ]
